/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorTelefono;
import ec.edu.ups.controlador.ControladorUsuario;
import ec.edu.ups.dao.TelefonoDao;
import ec.edu.ups.dao.UsuarioDao;
import ec.edu.ups.modelo.Telefono;
import ec.edu.ups.modelo.Usuario;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Anahi
 */
public class VentanaTelefono extends javax.swing.JFrame {
    private UsuarioDao usuarioDao = new UsuarioDao();
    private TelefonoDao telefonoD = new TelefonoDao();

    private ControladorUsuario control = new ControladorUsuario(usuarioDao, telefonoD);
    private Telefono telefono;
    private Usuario usuario;

    private ControladorTelefono ctrl = new ControladorTelefono(telefonoD);
    private Ventana3 ventanaListar;

    /**
     * Creates new form VentanaTelefono
     */
    public VentanaTelefono(Usuario usuario) {
        initComponents();
        setLocation(500, 200);
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTele = new javax.swing.JPanel();
        labelV2 = new javax.swing.JLabel();
        label2V2 = new javax.swing.JLabel();
        label3V2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt1V2 = new javax.swing.JTextField();
        txt2V2 = new javax.swing.JTextField();
        txt3V2 = new javax.swing.JTextField();
        txt4V2 = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelTele.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro de Teléfono", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 14), new java.awt.Color(153, 153, 255))); // NOI18N

        labelV2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelV2.setForeground(new java.awt.Color(102, 102, 255));
        labelV2.setText("Codigo");

        label2V2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label2V2.setForeground(new java.awt.Color(102, 102, 255));
        label2V2.setText("Numero");

        label3V2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        label3V2.setForeground(new java.awt.Color(102, 102, 255));
        label3V2.setText("Tipo");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("Operadora");

        btnCrear.setForeground(new java.awt.Color(51, 51, 255));
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnListar.setForeground(new java.awt.Color(51, 51, 255));
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTeleLayout = new javax.swing.GroupLayout(panelTele);
        panelTele.setLayout(panelTeleLayout);
        panelTeleLayout.setHorizontalGroup(
            panelTeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTeleLayout.createSequentialGroup()
                .addGroup(panelTeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelTeleLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelTeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelV2)
                            .addComponent(label2V2)
                            .addComponent(label3V2)
                            .addComponent(jLabel1))
                        .addGap(43, 43, 43)
                        .addGroup(panelTeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt1V2)
                            .addComponent(txt2V2)
                            .addComponent(txt3V2)
                            .addComponent(txt4V2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
                    .addGroup(panelTeleLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnListar, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        panelTeleLayout.setVerticalGroup(
            panelTeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTeleLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(panelTeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelTeleLayout.createSequentialGroup()
                        .addGroup(panelTeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelV2)
                            .addComponent(txt1V2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelTeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label2V2)
                            .addComponent(txt2V2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(label3V2))
                    .addComponent(txt3V2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelTeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt4V2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(panelTeleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTele, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String num = txt2V2.getText();
        String opera = txt4V2.getText();
        String tipo = txt3V2.getText();
        String id = txt1V2.getText();

        if (num == null || opera == null || tipo == null || id == null) {
            JOptionPane.showMessageDialog(null,"Usted no ha llenado todos los campos", "Error",JOptionPane.ERROR_MESSAGE);
        } else {
            this.ingresoTelefono();
            this.crearTelefono(usuario);

        }
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        List<Telefono> telefonos = usuario.getListaTelefonos();
        String[] teles= new String[telefonos.size()];
        for(int i=0;i<telefonos.size();i++){
            Telefono t = telefonos.get(i);
            if(t!=null){
                teles[i] = t.toString();
            }
        }
        System.out.println("lista\n " + telefonos);
        
        if (ventanaListar == null) {

            ventanaListar = new Ventana3(teles);
        }
        ventanaListar.setVisible(true);
        
    }//GEN-LAST:event_btnListarActionPerformed
    public void crearTelefono(Usuario usuario) {
        int codigo = Integer.parseInt(txt1V2.getText());

        telefono = ctrl.encontrarTelefono(codigo);

        control.crearTelefono(usuario, telefono);

        JOptionPane.showMessageDialog(this, "Su telefono se ha creado correctamente");
    }
    public void ingresoTelefono() {
        String num= txt2V2.getText();
        String ope = txt4V2.getText();
        String tipo = txt3V2.getText();
        int id = Integer.parseInt(txt1V2.getText());

        telefono = new Telefono(id, num, tipo, ope);
        ctrl.crearTelefono(telefono);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label2V2;
    private javax.swing.JLabel label3V2;
    private javax.swing.JLabel labelV2;
    private javax.swing.JPanel panelTele;
    private javax.swing.JTextField txt1V2;
    private javax.swing.JTextField txt2V2;
    private javax.swing.JTextField txt3V2;
    private javax.swing.JTextField txt4V2;
    // End of variables declaration//GEN-END:variables
}
